-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.customers
(
    customerid serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default",
    phone character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT customers_pkey PRIMARY KEY (customerid)
);

CREATE TABLE IF NOT EXISTS public.deliveries
(
    deliveryid serial NOT NULL,
    orderid integer NOT NULL,
    deliverydate date NOT NULL DEFAULT CURRENT_DATE,
    invoicenumber character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT deliveries_pkey PRIMARY KEY (deliveryid)
);

CREATE TABLE IF NOT EXISTS public.deliveryitems
(
    deliveryitemid serial NOT NULL,
    deliveryid integer NOT NULL,
    productid integer NOT NULL,
    deliveredqty integer NOT NULL,
    CONSTRAINT deliveryitems_pkey PRIMARY KEY (deliveryitemid)
);

CREATE TABLE IF NOT EXISTS public.orderitems
(
    orderitemid serial NOT NULL,
    orderid integer NOT NULL,
    productid integer NOT NULL,
    quantity integer NOT NULL,
    amount numeric(10, 2) NOT NULL,
    CONSTRAINT orderitems_pkey PRIMARY KEY (orderitemid)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    orderid serial NOT NULL,
    customerid integer NOT NULL,
    orderdate date NOT NULL DEFAULT CURRENT_DATE,
    totalamount numeric(10, 2) NOT NULL,
    CONSTRAINT orders_pkey PRIMARY KEY (orderid)
);

CREATE TABLE IF NOT EXISTS public.products
(
    productid serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    price numeric(10, 2) NOT NULL,
    stockqty integer NOT NULL,
    CONSTRAINT products_pkey PRIMARY KEY (productid)
);

ALTER TABLE IF EXISTS public.deliveries
    ADD CONSTRAINT deliveries_orderid_fkey FOREIGN KEY (orderid)
    REFERENCES public.orders (orderid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.deliveryitems
    ADD CONSTRAINT deliveryitems_deliveryid_fkey FOREIGN KEY (deliveryid)
    REFERENCES public.deliveries (deliveryid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.deliveryitems
    ADD CONSTRAINT deliveryitems_productid_fkey FOREIGN KEY (productid)
    REFERENCES public.products (productid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.orderitems
    ADD CONSTRAINT orderitems_orderid_fkey FOREIGN KEY (orderid)
    REFERENCES public.orders (orderid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.orderitems
    ADD CONSTRAINT orderitems_productid_fkey FOREIGN KEY (productid)
    REFERENCES public.products (productid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT orders_customerid_fkey FOREIGN KEY (customerid)
    REFERENCES public.customers (customerid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;